OPTIONS  http://kefo-azure-cors.azurewebsites.net/Bar
Origin: "https://www.kefo.no"
Access-Control-Request-Method: POST
Access-Control-Request-Headers: X-Money

### Returns 405

OPTIONS http://kefo-azure-cors.azurewebsites.net/Bar
Origin: "https://appservice.kefo.no"
Access-Control-Request-Method: POST
Access-Control-Request-Headers: X-Money

### 200 OK

OPTIONS  http://kefo-azure-cors.azurewebsites.net/Bar
Origin: "https://local.kefo.no"
Access-Control-Request-Method: POST
Access-Control-Request-Headers: X-Money

### Returns 204 No Content and that is OK

OPTIONS  http://kefo-azure-cors.azurewebsites.net/Bar
Origin: "https://local.kefo.no"
Access-Control-Request-Method: POST

###

POST http://kefo-azure-cors.azurewebsites.net/Bar
Origin: "https://local.kefo.no"
X-MONEY: 100

### 200 should contain X-BEER


# returns 400
curl -X OPTIONS --location "http://kefo-azure-cors.azurewebsites.net/Bar" \
-H "Origin: "https://www.kefo.no"" \
-H "Access-Control-Request-Method: POST" \
-H "Access-Control-Request-Headers: X-Money" -v

# returns 200
curl -X OPTIONS --location "http://kefo-azure-cors.azurewebsites.net/Bar" \
    -H "Origin: "https://appservice.kefo.no"" \
    -H "Access-Control-Request-Method: POST" \
    -H "Access-Control-Request-Headers: X-Money" -v